website/auth.py
# auth.py

# Code description: This file contains the code for the signup page. It checks if the user already exists in the database and if not, it creates a new user. It also checks if the email or username already exists in the database. If it does, it will flash an error message and redirect the user to the signup page. If the user is successfully created, it will redirect the user to the home page.


from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify, session, make_response
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from website.model import userinfo, Game, UserGame, Platform, db
from website.steam import steam_api, api_key, get_owned_games
import requests
from sqlalchemy import exists, and_
from website.forms import SignupForm



auth = Blueprint('auth', __name__)


@auth.route('/', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))

    form = SignupForm()

    if form.validate_on_submit():
        email = form.email.data
        name = form.name.data
        password = form.password.data

        # Check if email or name already exists in the database
        user_email = userinfo.query.filter_by(email=email).first()
        if user_email:
            flash('Email already exists', category='error')
            return redirect(url_for('auth.signup'))

        user_name = userinfo.query.filter_by(name=name).first()
        if user_name:
            flash('Username already exists', category='error')
            return redirect(url_for('auth.signup'))

        # Create a new userinfo object and add it to the database
        new_user = userinfo(email=email, name=name, password=generate_password_hash(password, method='sha256'))
        
        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Account created', category='success')
            return redirect(url_for('auth.login'))
        except Exception as e:
            print(str(e))
            db.session.rollback()
            flash('An error occurred while creating your account. Please try again later', category='error')
            return redirect(url_for('auth.signup'))

    return render_template('index.html', form=form)

#  Login Feature 
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = userinfo.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('views.home'))
        else:
            flash('Incorrect email or password', category='error')

    return render_template('login.html')

# Logout Feature
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template('index.html')

# Get all games
@auth.route('/get_all_games', methods=['GET'])
@login_required
def get_all_games():
    games = Game.query.filter_by(user_id=current_user.get_id()).all()
    games = [{'id': game.id, 'name': game.name, 'genre': game.genre, 'console': game.console,
              'completed': game.completed, 'recommend': game.recommend} for game in games]
    return jsonify(games)


@auth.route("/steam_login")
def steam_login():
    return redirect(f"https://steamcommunity.com/openid/login?openid.ns=http://specs.openid.net/auth/2.0&openid.mode=checkid_setup&openid.return_to={url_for('auth.authorized', _external=True)}&openid.realm={request.host_url}&openid.ns.sreg=http://openid.net/extensions/sreg/1.1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.identity=http://specs.openid.net/auth/2.0/identifier_select")


@auth.route("/authorized")
@login_required
def authorized():
    steam_id = request.args.get("openid.identity").split("/")[-1]
    session["steam_user"] = {"steamid": steam_id}

    # Get the current user from the database
    user = current_user

    # Check if a platform with the given steam_id already exists for the user
    existing_platform = Platform.query.filter_by(
        user_id=user.id, name='Steam').first()

    if existing_platform is None:
        # Create a new platform object and add it to the user's list of connected platforms
        platform = Platform(name='Steam', user_id=user.id,
                            connected=True, key=steam_id)
        db.session.add(platform)
        user.platforms.append(platform)
        platform_key = steam_id
    else:
        # Update the existing platform with the new values
        existing_platform.connected = True
        existing_platform.key = steam_id
        platform_key = existing_platform.key

    # Set a session variable to remember that the user has connected their Steam account
    session["steam_connected"] = True

    # Get owned games for the platform
    get_owned_games(platform_key=platform_key)

    # Commit the changes to the database
    db.session.commit()

    return redirect(url_for("auth.account"))


@auth.route('/steam_disconnect', methods=['POST'])
@login_required
def steam_disconnect():
    # Get the current user from the database
    user = current_user

    # Get the platform to disconnect
    platform = Platform.query.filter_by(user_id=user.id, name='Steam').first()

    if platform:
        # Delete all user_games associated with the platform
        num_deleted = UserGame.query.filter_by(platform_id=platform.id).delete()

        # Delete the games associated with the platform
        Game.query.filter_by(platform_id=platform.id).delete()

        # Delete the platform
        db.session.delete(platform)
        db.session.commit()

        flash(f"You have successfully disconnected from the {platform.name} platform.", category='success')
    else:
        flash('You are not currently connected to the Steam platform.', category='danger')

    return redirect(url_for('auth.account'))




@auth.route('/account')
@login_required
def account():
    user_platforms = current_user.platforms
    
    steam_connected = False
    for platform in user_platforms:
        if platform.name == 'Steam' and platform.connected:
            steam_connected = True
    
    return render_template('account.html', platforms=user_platforms, steam_connected=steam_connected)

website/templates/account.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<style>
#btn{
  border: none;
  border-radius: 9px;
  color: #fdf2eg;
  cursor: pointer;
  font-size: 16px;
  padding: 5px;
  transition: all 0.2s ease-in-out;
  margin-left: 10px;
  height: 15%;
 
  
} 
</style>
  <header class="header ">
    <div class="logo-container">
      <a href="#">
        <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
      </a>
    </div>

    <nav class="home-nav">
      <ul class="home-nav-list">
        <li><a class="home-nav-link" href="/home">Your Games</a></li>
        <li><a class="home-nav-link" href="/archive">Archive</a></li>
        <li><a class="home-nav-link" href="/leaderboard">Leaderboard</a></li>
        <li><a class="home-nav-link text-line" href="#">My Account</a></li>
        <li><a class="home-nav-link" href="/help">Help</a></li>
        <li><a class="home-nav-link" href="/logout">Logout</a></li>
      </ul>
    </nav>
  </header>

  <section>
  <div class="container">
    <div class="account">
  <h1>Account Information</h1>
  <p class="font-size">Username: {{ current_user.name }}</p>
  <p class="font-size">Email: {{ current_user.email }}</p>

  {% if current_user.has_platform('Steam') %}
    {% if 'steam_user' in session %}
      <p>Steam ID: {{ session['steam_user']['steamid'] }}</p>
    {% endif %}
    
    <form action="{{ url_for('auth.steam_disconnect') }}" method="post">
      <div class="flex">
      <input type="hidden" name="_method" value="DELETE">
      <img src="{{ url_for('static', filename='images/steam-icon.png') }}" alt="Steam Icon" style="width: 3.5rem; height: 3.5rem; vertical-align: middle; margin-right: 1rem;">
      <button type="submit" id="btn">Disconnect Steam Account</button>
     </div>
    </form>
  {% else %}
    <p>Not connected to Steam</p>
    <div class="flex">
    <img src="{{ url_for('static', filename='images/steam-icon.png') }}" alt="Steam Icon" style="width: 3.5rem; height: 3.5rem; vertical-align: middle; margin-right: 1rem;">
    <a class="steam-text" href="{{ url_for('auth.steam_login') }}">Connect Steam Account</a>
    </div>
  {% endif %}
</div>
  </div>
</section>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Always include this line of code!!! -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap"
      rel="stylesheet"
    />

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/general.css') }}">

    <script
      type="module"
      src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule=""
      src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.js"
    ></script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css" />

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
    
    <script src="{{ url_for('static', filename='vgarchive.js') }}"></script>
    

    <script defer src="// https://unpkg.com/smoothscroll-polyfill@0.4.4/dist/smoothscroll.min.js"> </script>
    <script defer src="{{ url_for('static', filename='script.js') }}"></script>

    <script src="https://kit.fontawesome.com/176d58561d.js" crossorigin="anonymous"></script>

    <title>{% block title %}My Website{% endblock %}</title>
    {% block header %}{% endblock %}
  </head>
  <body>

    {% block content %}{% endblock %}
  </body>
</html>

website/templates/help.html
{% extends 'base.html' %}

{% block title %}Archive Page{% endblock %}

{% block content %}
  <body>

    <header class="header ">
      <div class="logo-container">
        <a href="#">
          <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
        </a>
      </div>
  
      <nav class="home-nav">
        <ul class="home-nav-list">
          <li><a class="home-nav-link" href="/home">Your Games</a></li>
          <li><a class="home-nav-link" href="/archive">Archive</a></li>
                  <li><a class="home-nav-link" href="/leaderboard">Leaderboard</a></li>
        <li><a class="home-nav-link" href="/account">My Account</a></li>
          <li><a class="home-nav-link text-line" href="#">Help</a></li>
          <li><a class="home-nav-link" href="/logout">Logout</a></li>
        </ul>
      </nav>
    </header>  
  </body>
</html>


<html>
<head>
  <div class="color">
	<title>Game Tracking Website Help</title>
	<meta charset="utf-8">
	
	<h1>Welcome to our game tracking website!</h1>

	<p>We are excited to help you keep track of your favorite games and stay up-to-date on the latest news and updates. Here are some tips to help you get started:</p>

	<h2>How to create an account:</h2>

	<p>To create an account, click on the "Sign up" button in the top right corner of the screen. Fill in your email address and choose a password. You will receive a confirmation email to verify your account.</p>

	<h2>How to add a game to your tracking list:</h2>

	<p>Once you're logged in, go to the "Games" page and search for the game you want to track. Click on the "Track" button to add it to your tracking list. You will receive notifications when there are updates or news about your tracked games.</p>

	<h2>How to customize your profile:</h2>

	<p>To customize your profile, go to the "Profile" page and click on the "Edit Profile" button. You can upload a profile picture, add a bio, and customize your notification settings.</p>

	<h2>How to use the search feature:</h2>

	<p>To search for a game or news article, use the search bar located in the top right corner of the screen. You can search for games by title or platform, and news articles by keyword or topic.</p>

	<h2>How to contact support:</h2>

	<p>If you have any questions or issues, you can contact our support team by clicking on the "Contact" button in the footer of the website. Fill out the form with your name, email, and message, and we will get back to you as soon as possible.</p>

	<p>Thank you for using our game tracking website!</p>
  </div>

</body>
</html>

{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<head>
<style>

#submit-btn{
  border: none;
  border-radius: 9px;
  color: #fdf2eg;
  cursor: pointer;
  font-size: 16px;
  padding: 5px;
  transition: all 0.2s ease-in-out;
  margin-left: 10px;
  height: 15%;
 
  
}  
.search-form{
  
  text-decoration: none;
  color: #e9e6e6;
  font-weight: 500;
  font-size: 3rem;
  transition: all 0.3s;
 
  
}
#search-input{
  
  width: 20rem;
  height: 3rem;
  font-size: 20px;
  margin-left: 5px;
  margin-top: 5px;
  margin-right: 5px;
  
  
 
  
}
  
#toggle-games-btn{
  border: none;
  border-radius: 9px;
  color: #fdf2eg;
  cursor: pointer;
  font-size: 16px;
  padding: 5px;
  transition: all 0.2s ease-in-out;
  margin-left: 5px;
  height: 15%;
 
  
}

.search-form{
  width: 100%; /* Adjust the width as needed */
    
}

</style>
  
</head>
  <header class="header ">
    <div class="logo-container">
      <a href="#">
        <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
      </a>
    </div>

    <nav class="home-nav">
      <ul class="home-nav-list">
        <li><a class="home-nav-link text-line" href="#">Your Games</a></li>
        <li><a class="home-nav-link" href="/archive">Archive</a></li>
        <li><a class="home-nav-link" href="/leaderboard">Leaderboard</a></li>
        <li><a class="home-nav-link" href="/account">My Account</a></li>
        <li><a class="home-nav-link" href="/help">Help</a></li>
        <li><a class="home-nav-link" href="/logout">Logout</a></li>
      </ul>
    </nav>
  
  </header>

  <div class="padding">
  <h1 class="gray-color"> Welcome to the Timeline {{ username }}! </h1>

  <form class="search-form" action="{{ url_for('views.home') }}" method="POST">
    {{ form.csrf_token }}
    {{ form.search.label }} {{ form.search(id='search-input') }} {{ form.submit(id='submit-btn') }}
  

    <!-- Add this button element -->
    <button  id="toggle-games-btn" type="submit" name="toggle-games-btn" data-show-games="{% if session.show_games %}true{% else %}false{% endif %}">
      {% if session.show_games %}
        Hide My Games
      {% else %}
        Show My Games
      {% endif %}
    </button>        
</form>
  </div>

{% if session.show_games %}
  <div class="bottom"> 
    <div class="game-lists">
      <div class="game-list">
        <h2>Your Games</h2>
        {% if games %}
        {% for game, playtime, last_played, completion_achievements, total_achievements in games %}
        <div class="game">
            {% if game.image_url %}
          <div class="your-games">
            <img src="{{ game.image_url }}" alt="{{ game.name }} image" class="my-game-img" width="250" height="150"/>
          <div class="game-property"><strong>Game Title:</strong><div class="completion-info"><div class="completion-info"><span class="game-name">{{ game.name }}</span></div></div></div>
          {% endif %}
            <div class="game-property"><strong>Genre:</strong> {{ game.genre }}</div>
            <div class="game-property"><strong>Recommended:</strong> {{ game.recommend }}</div>
            <div class="game-property"><strong>Platform:</strong> {{ game.console }}</div>
            {% if playtime %}
              <div class="game-property"><strong>Playtime:</strong> 
                {{ playtime }} minutes</div>
            {% endif %}
            {% if completion_achievements != 0 and total_achievements != 0 %}

  <div class="game-property">
    <strong>Achievements completion:</strong>
    <div class="completion-info">
      {{ completion_achievements }} out of {{ total_achievements }}
    </div>
  </div>
{% endif %}
{% if last_played %}
            <div class="game-property"><strong>Last Played:</strong><div class="completion-info"> {{ last_played }}</div></div>
            {% endif %}
          </div>
        </div>
      {% endfor %}
      
        {% else %}
          <p>No games found based on your search query.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endif %}
  
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

  <body>
    <header class="header1 sticky">
      <a href="#home">
        <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
      </a>

      <nav class="main-nav">
        <ul class="main-nav-list">
          <li><a class="main-nav-link" href="#home">Home</a></li>
          <li><a class="main-nav-link" href="#aboutus">About us</a></li>
          <li><a class="main-nav-link" href="/login">Log In</a></li>
        </ul>
      </nav>
    </header>

    <main>
      <section class="section-hero" id="home">
        <h1 class="heading-primary">
          A fun way to collect your games!
            </h1>
        <div class="hero">
<div class="hero-text-box">
  <div class="hero-description-container">
    <p class="hero-description">Starting being a game pro by managing your data!</p>
    <img class="hero-image" src="{{ url_for('static', filename='images/timeline.PNG') }}" alt="demo"/>
  </div>
  <a href="#signup" class="btn btn--full margin-right-sm">Sign up Now!</a>
  <a href="#aboutus" class="btn btn--outline">Learn more &darr;</a>
</div>
        </div>
        </section>

        <section class="features" id="spotlight">
          <div class="container section-color">
              <div class="about-text">
          <span> Spotlight Games!</span>
              </div>
                     <!-- CS BOX in here  -->
            <div class="gallery-container">
            <div class="gallery">
  <a target="_blank" >
    <img src="{{ url_for('static', filename='images/arksurvivalworld.jpg') }}" alt="one" width="600" height="400">
  </a>
</div>

<div class="gallery">
  <a target="_blank" >
    <img src="{{ url_for('static', filename='images/deadbydaylight.jpeg') }}" alt="two" width="600" height="400">
  </a>
</div>

<div class="gallery">
  <a target="_blank" >
    <img src="{{ url_for('static', filename='images/warframelastwish.jpeg') }}" alt="three" width="600" height="400">
  </a>
</div>

<div class="gallery">
  <a target="_blank" >
    <img src="{{ url_for('static', filename='images/flightsimulatorx.jpeg') }}" alt="four" width="600" height="400">
  </a>
  </div>
  
  <div class="gallery">
  <a target="_blank" >
    <img src="{{ url_for('static', filename='images/valheim.jpeg') }}" alt="five" width="600" height="400">
  </a>
  </div>
            </div>
      
      </div>
</section>

      
      
        <section id="signup">
          <div class="container section-color">
            <div class="sign">
              <div class="sign-text-box">
                <h2 class="heading-secondary">Register Account</h2>
              
              <div>
                <form class="sign-form" id="signup-form" method="POST" action="{{ url_for('auth.signup') }}">
                  <div>
                    <label for="email">Email<br></label>
                    <input id="email" name="email" type="text" class="email-field" placeholder="ex: me@example.com" required>
                  </div>
                  <div>
                    <label for="username">Username<br></label>
                    <input id="username" type="text" name="name" class="username-field" placeholder="ex: MrPotatoChip" required>
                  </div>
                  <div class="last-input">
                    <label for="password">Password<br></label>
                    <input id="password" type="password" name="password" placeholder="do not share!" required>
                  </div>
                  <button class="btn-sign" id="submit-signup" type="submit">Register<br></button>
                </form>
              </div>                
          </div>
            </section>
              

<section id="aboutus">
          <div class="container container-line section-color">
            <div class="about-us-one">
              <div class="about-text">
                <section>
        <!--was generated with the assistance of chatgpt-->
			<h3> About Us </h3>
			<p>WI5DOM is an application that provides all users the ability to log games. Our team of experienced developers         and designers are passionate about creating high-quality applications that are tailored to the unique needs of our       clients.</p>
			<h3>Our Mission</h3>
			<p>At WI5DOM, our mission is to help businesses succeed by providing them with the tools and expertise they need         to thrive in the digital marketplace. We believe that a great website can be a game-changer for businesses, and we       are committed to helping our clients achieve their goals.</p>
			<h3>Contact Us</h3>
			<p>If you're interested in learning more about WI5DOM, please don't hesitate to get in touch. You can reach us by         phone at 123-456-7890 or by email at WI5DOM@help.com.</p>
		</section>
          

          </div>
        </div>
        </div>
        </div>
        </section> 
          

          </div>
        </div>
        </div>
        </div>
        </section> 
            <footer class="footer ">
          <div class="container container-3 grid grid--footer ">
            <div class="logo-col">
              <a href="#" class="footer-logo">
                <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
                </a>
                <ul class="social-links">
                  <li><a class="footer-link" href="#"><ion-icon class="social-icon" name="logo-instagram"></ion-icon></a></li>
                  <li><a class="footer-link" href="#"><ion-icon class="social-icon"  name="logo-facebook"></ion-icon></a></li>
                  <li><a class="footer-link" href="#"><ion-icon class="social-icon"  name="logo-twitter"></ion-icon></a></li>
                </ul>
                <p class="copyright">Copyright &copy; 2023 by W15DOM, Inc All rights reserved.</p>
            </div>
            <div class="address-col">
              <p class="footer-heading">Contact us</p>
              <address class="contacts">
              <p class="address">1301 E Anderson Ln, Suite 200, Austin, TX 78752</p>
              <p>
              <a class="footer-link" href="tel:415-201-6370">123-456-7890</a><br />
              <a class="footer-link" href="mailto:hello@omnifood.com">WI5DOM@help.com</a>
              </p>
            </address>
            </div>
            <nav class="nav-col">
              <p class="footer-heading">Account</p>
              <ul class="footer-nav">
                <li><a class="footer-link" href="#signup">Create account</a></li>
                <li><a class="footer-link" href="/login">Sign in</a></li>
              </ul>
            </nav>
            <nav class="nav-col">
              <p class="footer-heading">Company</p>
              <ul class="footer-nav">
                <li><a class="footer-link" href="#aboutus">About W15DOM</a></li>
              </ul>
            </nav>
            <nav class="nav-col">
              <p class="footer-heading">Resources</p>
              <ul class="footer-nav">
                <li><a class="footer-link" href="#aboutus">Help center</a></li>
                <li><a  class="footer-link" href="#aboutus">Privacy & terms</a></li>
              </ul>
            </nav>
          </div>
        </footer>
                      
</body>
</html>

{% endblock %}

website/templates/leaderboard.html
{% extends 'base.html' %}

{% block title %}Leaderboard{% endblock %}

{% block content %}
<header class="header">
  <div class="logo-container">
    <a href="#">
      <img
        class="logo"
        alt="W15DOM logo"
        src="{{ url_for('static', filename='images/w15domlogo.png') }}"
      />
    </a>
  </div>

  <nav class="home-nav">
    <ul class="home-nav-list">
      <li><a class="home-nav-link" href="/home">Your Games</a></li>
      <li><a class="home-nav-link" href="/archive">Archive</a></li>
      <li><a class="home-nav-link text-line" href="#">Leaderboard</a></li>
      <li><a class="home-nav-link" href="/account">My Account</a></li>
      <li><a class="home-nav-link" href="/help">Help</a></li>
      <li><a class="home-nav-link" href="/logout">Logout</a></li>
    </ul>
  </nav>
</header>

<main>
  <h1 class="leaderboard-title">Top 5 Most Played Games</h1>
  <div class="leaderboard-games">
    {% for game in games %}
    <div class="game-container">
      <div class="game-image-wrapper">
      <img
        src="{{ game.image_url }}"
        alt="{{ game.name }} image"
        class="game-image"
      />
    </div>
      <div class="game-name">{{ game.game_name }}</div>

      <div class="game-info">
        <div>Rank: {{ loop.index }}</div>
        <div>Playtime: {{ game.total_playtime }} mins</div>
        <div><i class="fa-solid fa-thumbs-up icon-large"></i>  {{ game.total_likes }}</div>
        <div><i class="fa-solid fa-thumbs-down icon-large"></i>  {{ game.total_dislikes }}</div>
      </div>
    </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <style>
    .section-login input{
      color: black; !important
    }
  </style>

  <section class="section-login">
    <div class="container-login">
      <div class="sign">
        <div class="login-text-box">
          <h2 class="heading-secondary gray-color">Log In</h2>
          <form class="sign-form" method="POST">
            <div>
              <div class="gray-color">
                <label for="email">Email</label>
                <input id="email" name="email" type="text" class="email-field" placeholder="ex: me@example.com" required>
              </div>
            </div>
            <div class="last-input gray-color">
              <label for="password">Password</label>
              <input id="password" type="password" name="password" placeholder="do not share!" required>
            </div>
            <div class="grid-cols-2">
              <button class="btn-sign" type="submit">Login</button>
              <a href="/" class="btn-sign btn-back">Back</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

website/templates/message.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <header class="header ">
    <div class="logo-container">
      <a href="#">
        <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
      </a>
    </div>

    <nav class="home-nav">
      <ul class="home-nav-list">
        <li><a class="home-nav-link" href="/home">Your Games</a></li>
        <li><a class="home-nav-link" href="/archive">Archive</a></li>
        <li><a class="home-nav-link text-line" href="#">Leaderboard</a></li>
        <li><a class="home-nav-link" href="/account">My Account</a></li>
        <li><a class="home-nav-link" href="/help">Help</a></li>
        <li><a class="home-nav-link" href="/logout">Logout</a></li>
      </ul>
    </nav>
  </header>

{% endblock %}

website/templates/vgarchive.html
{% extends 'base.html' %}

{% block title %}Archive Page{% endblock %}

{% block content %}
  <body>
           <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
          <link rel="stylesheet" href="{{ url_for('static', filename='css/vgarchive.css') }}">

    <header class="header ">
      <div class="logo-container">
        <a href="#">
          <img class="logo" alt="W15DOM logo" src="{{ url_for('static', filename='images/w15domlogo.png') }}" />
        </a>
      </div>
  
      <nav class="home-nav">
        <ul class="home-nav-list">
          <li><a class="home-nav-link" href="/home">Your Games</a></li>
          <li><a class="home-nav-link text-line" href="#">Archive</a></li>
          <li><a class="home-nav-link" href="/leaderboard">Leaderboard</a></li>
          <li><a class="home-nav-link" href="/account">My Account</a></li>
          <li><a class="home-nav-link" href="/help">Help</a></li>
          <li><a class="home-nav-link" href="/logout">Logout</a></li>
        </ul>
      </nav>
    </header>

    <div class="Game-title">
    <h1>WI5DOM Video Game Archive</h1>
    </div>
    <div class="archive">
      <form id="game-form" method="POST" action="{{ url_for('views.archive') }}">
        <input type="hidden" id="game-id" value="">
        <label for="name-input">Name:</label>
        <input class="VGName" type="text" id="name-input" name="name">
        <label for="genre-input">Genre:</label>
        <input class="VGgenre" type="text" id="genre-input" name="genre">
        <label for="console-input">Console:</label>
        <input class="VGconsole" type="text" id="console-input" name="console">
        <label for="completed-input">Completed:</label>
        <input type="checkbox" id="completed-input" name="completed">
        <label for="recommend-input">Recommend:</label>
        <input type="checkbox" id="recommend-input" name="recommend">
        <button class="submit">Add Game</button>
      </form>      
    </div>
    <table id="game-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Genre</th>
          <th>Console</th>
          <th>Completed</th>
          <th>Recommended</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for game in games %}
        <tr>
          <td>{{ game.name }}</td>
          <td>{{ game.genre }}</td>
          <td>{{ game.console }}</td>
          <td>{{ 'Yes' if game.completed else 'No' }}</td>
          {% if game.recommend is none %}
          <td>unrated</td>
          {% elif game.recommend is true %}
          <td>Like</td>
          {% else %}
          <td>Dislike</td>
          {% endif %}
      
          <td>
            <button class="edit" data-id="{{ game.id }}">Edit</button>
            <button class="delete" data-id="{{ game.id }}">Delete</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
      
    </table>


{% endblock %}